# Generated by Django 4.0.3 on 2022-03-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_alter_demo_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=121)),
                ('sepal_length', models.TextField()),
                ('sepal_width', models.TextField()),
                ('petal_length', models.TextField()),
                ('petal_width', models.TextField()),
                ('result', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
